apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  MY_DATABASE_DRIVER: "mysql"
  DB_HOST: "mysql"
  DB_USER_NAME: "appuser"
  DB_NAME: "database"
  DB_PORT: "3306"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: backend
type: Opaque
stringData:
  DB_PASSWORD: "cambia-este-password"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: devops-exam-backend:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
