apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup-cronjob
  namespace: backend
spec:
  schedule: "0 */3 * * *" # Se ejecuta cada 3 horas (00:00, 03:00, 06:00, etc.)
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mysql-aws-backup
              image: amazon/aws-cli:latest
              command:
                - /bin/sh
                - -c
                - |
                  # 1. Instalar cliente mariadb/mysql
                  yum install -y mariadb105

                  # 2. Generar el nombre de archivo con timestamp
                  BACKUP_FILE="/tmp/${ALUMNO_APELLIDO}_backup_$(date +%Y%m%d%H%M%S).sql"

                  # 3. Hacer el dump de MySQL (--no-tablespaces evita la advertencia de permisos)
                  mysqldump -h "$DB_HOST" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" --no-tablespaces "$MYSQL_DATABASE" > "$BACKUP_FILE"

                  # 4. Subir el respaldo a AWS S3
                  aws s3 cp "$BACKUP_FILE" "s3://${BUCKET_NAME}/"
              env:
                - name: DB_HOST
                  value: "mysql"
                - name: BUCKET_NAME
                  value: "bucket-codigo-aws-backup"
                - name: ALUMNO_APELLIDO
                  value: "velasquez_cruz"
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: MYSQL_DATABASE
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: MYSQL_USER
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mysql-secret
                      key: MYSQL_PASSWORD
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_SECRET_ACCESS_KEY
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      name: aws-credentials
                      key: AWS_DEFAULT_REGION