name: Cambiar Driver de Base de Datos

on:
  workflow_dispatch:
    inputs:
      recurso:
        description: 'Recurso de Kubernetes (ej. deployment)'
        required: true
        default: 'deployment'
      driver:
        description: 'Selecciona el Driver de BD'
        required: true
        type: choice
        options:
          - mysql
          - postgres
          - mongo

jobs:
  actualizar-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          ref: modificador

      - name: Configurar kubectl
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.DO_KUBECONFIG }}

      - name: Aplicar cambio de driver en Kubernetes
        run: |
          echo "Actualizando el recurso ${{ github.event.inputs.recurso }}/backend en el namespace backend con el driver: ${{ github.event.inputs.driver }}"
          
          # Aquí '${{ github.event.inputs.recurso }}' tomará lo que escribas en la UI (ej. deployment)
          kubectl set env ${{ github.event.inputs.recurso }}/backend -n backend MY_DATABASE_DRIVER=${{ github.event.inputs.driver }}
          
          # Reinicio usando también el input dinámico
          kubectl rollout restart ${{ github.event.inputs.recurso }}/backend -n backend
          
          # Verificación
          kubectl get pods -n backend